### ISSUE TITLE
How to translate a new language?

### ISSUE THREAD

**Issue by tversteeg** [MrReSc/Headi#14]
Hi @MrReSc, thanks for this nice app. It's very useful.

How can I add a translation for a new language? It looks like I can only add translations for Esperanto and German on Crowdin. I would like to contribute some Dutch (and possibly Vietnamese in the future) translations.

**Comment by MrReSc** [comment]
I'm glad you like the app.

I have added more languages to Crowdin.
I'm really looking forward to your translations!

If you have any questions about translating, get in touch with me.

**Comment by tversteeg** [comment]
It seems the `strings.xml` is double? I filled out everything in one but it only says I completed 50%, while the other file contains exactly the same strings..

**Comment by MrReSc** [comment]
I'll have to take a look. I think it's because of a second branch. I will get back to you.

**Comment by MrReSc** [comment]
> It seems the `strings.xml` is double? I filled out everything in one but it only says I completed 50%, while the other file contains exactly the same strings..

Is fixed, thanks for your help!
