### ISSUE TITLE
Drop down menu on timer does not work

### ISSUE THREAD

**Issue by Electw** [MrReSc/Headi#17]
v1.10.3
Android 11, installed from F-Droid

The drop down menu on the timer does not show anything when the triangle is pressed, which prevents the timer from being used. The button recognizes taps, but doesn't show the menu.

https://user-images.githubusercontent.com/55963122/116286350-faf5eb00-a743-11eb-94e2-be114524e981.mp4

**Comment by MrReSc** [comment]
Hello, thanks for the message.
I have it running on Android 11.
Did you create a pain? If not, there are none available in the dropdown menu.

**Comment by Electw** [comment]
> Hello, thanks for the message.
> I have it running on Android 11.
> Did you create a pain? If not, there are none available in the dropdown menu.

I didn't realize you had to create a pain first. I added one, and now it works. Thanks for the help! Perhaps you could add a message on the timer screen to tell the user to create a pain first, it would make the app easier to use.

**Comment by MrReSc** [comment]
I actually wanted to do some onboarding. Unfortunately, I don't have time yet.
This message already exists. If there is no pain entry and the start button is pressed, the following message appears:

![Screenshot_20210428-081551.jpg](https://user-images.githubusercontent.com/24952268/116355631-68645300-a7fa-11eb-9072-a00a2dc9c412.jpg)

Probably I should show the message also when the dropdown menu is pressed.

**Comment by Electw** [comment]
I think if you put a message on where to add a type of pain it would help. I got that pop up message, but it didn't occur to me that I had to go to the pain section via the hamburger menu to do it.

**Comment by MrReSc** [comment]
I have tried to formulate the message in a more understandable way. Thank you for the advice.
