### ISSUE TITLE
Feature Request: Barometric pressure log/notifications.

### ISSUE THREAD

**Issue by Innomen** [MrReSc/Headi#18]
Title says it all. Just would like a graph of recent pressure changes I can overlay with headache data. Thanks for reading, great app. Appreciate it.

**Comment by MrReSc** [comment]
In principle, this is a very good idea. We have already discussed this once in Issue #15. I still have privacy concerns.
The idea of the app was to be as privacy-preserving as possible. Even though it's opt-in, every time you record, a request is made to a server with the geolaction.

If we can find a privacy-friendly solution, maybe we could implement it.

**Comment by Innomen** [comment]
Ahh ok, Well, thanks for considering it :) And answering :) Bravo on helping people! Headaches are criminally underrated as a source of suffering. I blame alcohol for making hangovers into a joke. (They aren't. AP kills.)

**Comment by MrReSc** [comment]
I'm happy to share my work, but thank you for the kind words.

Feel free to contribute to Headi if you like.
