### ISSUE TITLE
Some strings overlap with each other on the trend linechart

### ISSUE THREAD

**Issue by EasyVector** [MrReSc/Headi#20]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the timer page, **some strings overlap with each other on the trend linechart, and maybe the clock string is too huge so part of it is blocked as well**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 1.10.8, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that those texts are apart from each other, and I wish I could see the clock string fully. 

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting
2.open this app for the first time
3.this error could be seen

**Screenshot**

(The overlap and blocked part are notated in red)

<img src="https://user-images.githubusercontent.com/25502419/130750105-3e82fea0-9f9d-40fe-8d3c-b9fae7048a3c.png" alt="copy" width="250"/>

**Environment**

1. Version of Headi: 1.10.8
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by MrReSc** [comment]
I have removed the scroll from the diagram and reduced the number of labels on the Y-axis, as the scroll was also present in the standard size. I did not like that.
The release will be available in the F-Droid and Play Store in the next few days.

Thanks for your help.

![Bildschirmfoto vom 2021-08-27 16-07-36](https://user-images.githubusercontent.com/24952268/131142946-db5b5e5d-eaec-4313-b3d4-9126eb16e453.png)

**Comment by EasyVector** [comment]
It is very brilliant to reduce the numbers on the Y-axis, and I can't agree with you more. 
What I have done is mainly to eliminate this problem by reserving space for Y-axis which would inevitably leave a scroll bar when the size and the font are both normal because I am not quite familiar with this Chart package, so I have to say your modification is much better. If it is possible I would like to investigate a better way for problems just like this. Thank you for letting me know about this!! :)
