### ISSUE TITLE
Replace PDF icon in diary page to an oss friendly one

### ISSUE THREAD

**Issue by LeoColman** [MrReSc/Headi#24]
The current icon for the PDF (I believe it's in [this file](https://github.com/MrReSc/Headi/blob/master/app/src/main/res/drawable/ic_menu_pdf.xml)) is very similar to the [one from Adobe](https://www.adobe.com/misc/pdfs/TM_GuideforThirdPartiesFinalPrint.pdf) (p 6).

Adobe isn't exactly your open-source friendly company.

There are other icons that represent PDF, some even with just the letters `PDF`, which is also clearer than the PDF symbol.

What do you guys think?

This one looks like a good candidate
https://thenounproject.com/icon/pdf-2201522/

**Comment by MrReSc** [comment]
Hi Leo
I see your concerns. I actually thought I had only used icons from [https://materialdesignicons.com](https://materialdesignicons.com/). These have a harmless license.

Unfortunately, I can no longer find the corresponding PDF icon on the website.

When I find time again, I can replace it.

PS: Code contributions are welcome.
