### ISSUE TITLE
Sponsoring

### ISSUE THREAD

**Issue by LeoColman** [MrReSc/Headi#25]
Hey!
I want to donate to this project but I didn't find any sponsor link.

I'd like to recommend setting up a [Buy Me a Coffee
](https://www.buymeacoffee.com/) or similar and adding it to the readme (and to the app too, I'd suggest)

**Comment by MrReSc** [comment]
Thank you for your offer. I do not want money for it. I am more happy about code contributions or translations.
Since I have a job and a family I don't have the time to work on it. So if you can program too, you are welcome to work on it.
