### ISSUE TITLE
Text in the notification

### ISSUE THREAD

**Issue by MrReSc** [MrReSc/Headi#5]
The text in the notification should be more meaningful. It should be quicker to recognize which app it is.

**Comment by AmirAce** [comment]
Hey man, I made a commit for you, do you think its good?

**Comment by MrReSc** [comment]
Maybe it is enough to think of a better text. For this you would have to adjust the text in the [strings.xml](https://github.com/MrReSc/Headi/blob/6c361cb25432784e86775efec7c6814992d4046b/app/src/main/res/values/strings.xml#L31) file. But maybe you have to adapt the layout of the notification.
